//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solti.Utils.Json.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solti.Utils.Json.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid context.
        /// </summary>
        internal static string INVALID_CONTEXT {
            get {
                return ResourceManager.GetString("INVALID_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed {0} found (row: {1}, col: {2}). Reason: &quot;{3}&quot;.
        /// </summary>
        internal static string MALFORMED {
            get {
                return ResourceManager.GetString("MALFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Expected &quot;{0}&quot;, found &quot;{1}&quot; (row: {2}, col: {3})..
        /// </summary>
        internal static string MALFORMED_INPUT {
            get {
                return ResourceManager.GetString("MALFORMED_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max depth reached..
        /// </summary>
        internal static string MAX_DEPTH_REACHED {
            get {
                return ResourceManager.GetString("MAX_DEPTH_REACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing HEX digit.
        /// </summary>
        internal static string MISSING_HEX_DIGIT {
            get {
                return ResourceManager.GetString("MISSING_HEX_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing list item.
        /// </summary>
        internal static string MISSING_ITEM {
            get {
                return ResourceManager.GetString("MISSING_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing property.
        /// </summary>
        internal static string MISSING_PROP {
            get {
                return ResourceManager.GetString("MISSING_PROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a hex digit.
        /// </summary>
        internal static string NOT_HEX_DIGIT {
            get {
                return ResourceManager.GetString("NOT_HEX_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a number.
        /// </summary>
        internal static string NOT_NUMBER {
            get {
                return ResourceManager.GetString("NOT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected white space.
        /// </summary>
        internal static string UNEXPECTED_WHITE_SPACE {
            get {
                return ResourceManager.GetString("UNEXPECTED_WHITE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown control character.
        /// </summary>
        internal static string UNKNOWN_CTRL {
            get {
                return ResourceManager.GetString("UNKNOWN_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string.
        /// </summary>
        internal static string UNTERMINATED_STR {
            get {
                return ResourceManager.GetString("UNTERMINATED_STR", resourceCulture);
            }
        }
    }
}
